# Generated by Django 5.1.5 on 2025-03-18 19:18

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_until', models.DateTimeField(default=datetime.datetime(2025, 3, 22, 11, 0))),
                ('game_status', models.CharField(choices=[('disabled_until_time', 'Esperant a començar'), ('playing', 'Jugant'), ('paused', 'Pausat'), ('finished', 'Finalitzat')], default='disabled_until_time', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('birth_date', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('territori_zona', models.CharField(default='', max_length=50)),
                ('esplai', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('pending_registration', 'Pendent de registre'), ('waiting_for_circle', 'Esperant a formar part del cercle'), ('not_playing', 'No jugant'), ('alive', 'Viu'), ('pending_death_confirmation', 'Pendent de confirmació de mort'), ('dead', 'Mort'), ('last_player_standing', 'Últim jugador viu'), ('banned', 'Expulsat')], default='pending_registration', max_length=30)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AssassinationCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assassin', to='joc.player')),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_by', to='joc.player')),
            ],
        ),
        migrations.CreateModel(
            name='Assassination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField(choices=[(0, '0 - Expulsat'), (100, '100 - Esplai'), (150, '150 - Territori/Zona'), (200, '200 - MCECC'), (1000, '1000 - Últim jugador viu')], default=200)),
                ('killer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='joc.player')),
                ('victim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deaths', to='joc.player')),
            ],
        ),
    ]
