# Generated by Django 5.1.5 on 2025-03-19 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
    ]
