# Generated by Django 5.1.5 on 2025-03-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joc', '0002_remove_player_first_name_remove_player_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='profile_picture_url',
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
