# Generated by Django 5.1.5 on 2025-06-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joc', '0003_remove_player_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='esplai',
        ),
        migrations.RemoveField(
            model_name='player',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='player',
            name='territori_zona',
        ),
        migrations.AlterField(
            model_name='assassination',
            name='points',
            field=models.IntegerField(choices=[(0, '0 - Expulsat'), (200, '200 - Cas general'), (1000, '1000 - Últim jugador viu')], default=200),
        ),
    ]
