# Generated by Django 5.1.5 on 2025-06-16 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joc', '0004_remove_player_esplai_remove_player_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfig',
            name='disable_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 18, 0)),
        ),
    ]
