# Generated by Django 5.1.5 on 2025-07-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joc', '0005_alter_gameconfig_disable_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assassination',
            name='points',
            field=models.IntegerField(choices=[(0, '0 - Expulsat'), (1, '1 - Assassinat')], default=200),
        ),
    ]
