# Generated by Django 5.1.5 on 2025-07-12 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joc', '0006_alter_assassination_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfig',
            name='disable_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 13, 18, 0)),
        ),
    ]
